all:
  children:
    web:
      hosts:
        benjaminconnelly.com:
          ansible_host: 52.43.114.69
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/bconnelly_ryuk
          ansible_python_interpreter: /usr/bin/python3
